# Generated by Django 6.0.3 on 2026-03-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('pcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='pcs.chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.quiz'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.quiz'),
        ),
    ]
