# Generated by Django 6.0.3 on 2026-03-23 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('users', '0002_school_alter_user_role_user_default_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='users.school'),
        ),
    ]
