# Generated by Django 6.0.3 on 2026-03-17 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SEAL', 'Sealed Year'), ('DECRYPT', 'Decrypted Archive'), ('PRINT', 'Printed Archive'), ('FAILED_ATTEMPT', 'Failed Access Attempt')], max_length=20)),
                ('admin_email', models.CharField(max_length=255)),
                ('target_matricule', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SealedArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_matricule', models.CharField(db_index=True, max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('encrypted_document_url', models.CharField(max_length=500)),
                ('file_hash_sha256', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_by', models.CharField(max_length=255)),
            ],
        ),
    ]
