# Generated by Django 6.0.3 on 2026-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveaccesslog',
            name='school_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sealedarchive',
            name='school_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
