# Generated by Django 6.0.3 on 2026-04-04 19:56

from django.db import migrations, models


def backfill_resource_audiences(apps, schema_editor):
    Resource = apps.get_model("pcs", "Resource")
    for resource in Resource.objects.all().iterator():
        if not resource.target_audiences:
            resource.target_audiences = ["STUDENT"]
            if resource.status == "UNLOCKED" and resource.published_at is None:
                resource.published_at = resource.updated_at or resource.created_at
            resource.save(update_fields=["target_audiences", "published_at"])


def rollback_resource_audiences(apps, schema_editor):
    Resource = apps.get_model("pcs", "Resource")
    Resource.objects.filter(target_audiences=["STUDENT"]).update(target_audiences=[])


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0004_chapter_created_at_chapter_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ai_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='document_class',
            field=models.CharField(choices=[('PUBLIC_RESOURCE', 'Public Resource'), ('SCHOOL_COMMUNICATION', 'School Communication'), ('PEDAGOGICAL_RESTRICTED', 'Pedagogical Restricted'), ('OFFICIAL_ARCHIVE_VAULT', 'Official Archive Vault'), ('AI_TRAINING_CORPUS', 'AI Training Corpus')], default='PEDAGOGICAL_RESTRICTED', max_length=32),
        ),
        migrations.AddField(
            model_name='resource',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='target_audiences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_resource_audiences, rollback_resource_audiences),
    ]
