# Generated by Django 6.0.6 on 2026-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0005_resource_ai_eligible_resource_document_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('ANNALES', 'Annales'), ('CORRECTION', 'Corrigé'), ('NOTES', 'Notes de cours'), ('APPROFONDISSEMENT', 'Approfondissement'), ('OTHER', 'Autre')], default='OTHER', help_text='Taxonomie pédagogique : annales, corrigé, notes, approfondissement.', max_length=20),
        ),
    ]
