# Generated by Django 6.0.6 on 2026-06-12 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0006_resource_category'),
        ('sis', '0005_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='sis.classroom'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pcs.chapter'),
        ),
    ]
